language: cpp

compiler:
  - gcc

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build

script:
  # once CMake has done its job we just build using make as usual
  - make