language: cpp
compiler: gcc
dist: trusty

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script: 
  # Build and run this project
  - g++ *.cpp -g -std=c++17 -O3 -Wall -Wextra -pthread -pedantic -o posix
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 