name: C/C++ CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run random.sh
      run: |
         chmod +x ./.test/random.sh
         ./.test/random.sh
      shell: bash
    - name: Run empty_input.sh
      run: |
         chmod +x ./.test/empty_input.sh
         ./.test/empty_input.sh
      shell: bash
