# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
#  pull_request:
#    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#    - name: trigger single Job
#      uses: appleboy/jenkins-action@master
#      with:
#        url: "http://kel.osll.ru/jenkins/"
#        user: "ashahov"
#        token: "1145a05a95ace3cf275b2d2d301c78f046"
#        job: "echo-docker-pipeline"

    - name: "Trigger jenkins job"
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: "kel.osll.ru/jenkins"
        jenkins-token: "1145a05a95ace3cf275b2d2d301c78f046"
        user: "ashahov"
        job-path: "job/test-jobs/job/echo-docker-pipeline"
        job-params: "{'param1': 'value1', 'param2': 'value2'}"
    - name: Get job status
      run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"

