# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  your_job_name:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger posix CI job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "http://kel.osll.ru/jenkins/job/test-jobs/"
          jenkins_user: "ashahov"
          jenkins_token: "1145a05a95ace3cf275b2d2d301c78f046"
          job_name: "test-jobs/job/echo-docker-pipeline"
          job_params: '{"param_1":"value_1", "param_2":"value_2"}'
          job_timeout: "3600" # Default 30 sec. (optional)